name: Branch

on:
  pull_request:
    branches:
      - main

jobs:
  QualityChecks:
    name: 🧪  Quality Checks
    secrets: inherit
    uses: ./.github/workflows/_quality_checks.yml

  Dependabot:
    name: Dependabot
    needs: [QualityChecks]
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.4.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve and merge a PR
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    permissions:
      contents: write
      pull-requests: write
